[1510171] 2023-01-30T20:51:39 ~ <00000007>object_vector - Working folder "/home/scott/repo/ansar-create/test/framework"
[1510171] 2023-01-30T20:51:39 ~ <00000007>object_vector - Running object "__main__.an_object"
[1510171] 2023-01-30T20:51:39 ~ <00000007>object_vector - Class threads (1) "retries" (1)
[1510171] 2023-01-30T20:51:39 + <00000008>an_object - Created by <00000007>
^C



^CTraceback (most recent call last):
  File "ansar/create/framework.py", line 300, in create_object
  File "ansar/create/framework.py", line 240, in catch_control_c
ansar.create.framework.ControlC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ansar/create/framework.py", line 305, in create_object
  File "ansar/create/point.py", line 300, in send
  File "ansar/create/space.py", line 265, in send_a_message
  File "ansar/create/framework.py", line 240, in catch_control_c
ansar.create.framework.ControlC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 320, in wait
  File "ansar/create/framework.py", line 240, in catch_control_c
ansar.create.framework.ControlC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "queue.py", line 171, in get
  File "threading.py", line 320, in wait
  File "ansar/create/framework.py", line 240, in catch_control_c
ansar.create.framework.ControlC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_that_logs.py", line 38, in <module>
    ar.create_object(an_object, logs=ar.log_to_stderr)
  File "ansar/create/framework.py", line 334, in create_object
  File "ansar/create/root.py", line 102, in stop_root
  File "ansar/create/pending.py", line 248, in stop
  File "ansar/create/pending.py", line 244, in ask
  File "ansar/create/pending.py", line 217, in select
  File "ansar/create/pending.py", line 110, in pull
  File "ansar/create/pending.py", line 90, in get
  File "queue.py", line 165, in get
  File "threading.py", line 268, in __exit__
RuntimeError: release unlocked lock
[1510171] Failed to execute script 'object_that_logs' due to unhandled exception!
(.dev) scott@seneca:~/repo/ansar-create/test/framework$ 
